FROM php:7.3.26-fpm-buster as fpm

RUN set -ex \
    && { \
			apt-get update ; \
            apt-get install -y libpq-dev; \
            rm -rf /var/lib/apt/lists/*; \
       }

RUN docker-php-ext-install pdo pdo_pgsql pdo_mysql mysqli

RUN set -ex \
    && { \
			apt-get update ; \
            apt-get install -y libpng-dev libjpeg-dev libfreetype6-dev; \
            rm -rf /var/lib/apt/lists/*; \
       }

RUN docker-php-ext-configure gd \
        --with-freetype-dir=/usr/include/freetype2 \
        --with-png-dir=/usr/include \
        --with-jpeg-dir=/usr/include


RUN docker-php-ext-install gd \
    && docker-php-ext-enable opcache

RUN set -ex \
    && { \
            apt-get update ; \
            apt-get install -y libmemcached-dev; \
            rm -rf /var/lib/apt/lists/*; \
       }

RUN set -ex && \
    { \
            pecl install igbinary && \
            pecl install --nobuild memcached && \
            cd "$(pecl config-get temp_dir)/memcached" && \
            phpize && \
            ./configure --enable-memcached-igbinary && \
            make -j$(nproc) && \
            make install; \
    } && \
    docker-php-ext-enable igbinary memcached


RUN set -ex \
    && { \
			apt-get update ; \
            apt-get install -y zlib1g-dev libicu-dev; \
            rm -rf /var/lib/apt/lists/*; \
       }

RUN docker-php-ext-configure intl \
    && docker-php-ext-install intl

RUN set -ex && \
    { \
            pecl install xdebug; \
    }

RUN set -ex \
    && { \
        apt-get update ; \
        apt-get install -y libxml2-dev; \
        rm -rf /var/lib/apt/lists/*; \
        docker-php-ext-install soap; \
    }

RUN set -ex \
    && { \
        apt-get update ; \
        #apt-get install -y zlib1g-dev; \
        apt-get install -y libzip-dev libzip4; \
        docker-php-ext-configure zip --with-zlib-dir=/usr; \
        docker-php-ext-install zip; \
        rm -rf /var/lib/apt/lists/*; \
    }

FROM markkimsal/phusion-serverimage:0.11-debian-buster
RUN install_clean nginx

COPY --from=fpm /usr/local/ /usr/local/
COPY --from=fpm /usr/lib/x86_64-linux-gnu/libargon*.so.1   \
                /usr/lib/x86_64-linux-gnu/libxml*.so.2     \
                /usr/lib/x86_64-linux-gnu/libicu*.so.63    \
                /usr/lib/x86_64-linux-gnu/libsodium*.so.23 \
                /usr/lib/x86_64-linux-gnu/libsql*.so.0     \
                /usr/lib/x86_64-linux-gnu/libpng*.so       \
                /usr/lib/x86_64-linux-gnu/libjpeg*.so      \
                /usr/lib/x86_64-linux-gnu/libfreet*.so     \
                /usr/lib/x86_64-linux-gnu/libmemcached*.so \
                /usr/lib/x86_64-linux-gnu/
COPY --from=fpm /usr/lib/x86_64-linux-gnu/libpq*.so /usr/lib/x86_64-linux-gnu/

RUN ldconfig

COPY runit /etc/service/

WORKDIR /app
CMD ["/sbin/my_init"]
