FROM php:7.3.26-fpm-buster as fpm

RUN docker-php-ext-install mysqli pdo_mysql

# Add Microsoft repo for Microsoft ODBC Driver 13 for Linux
RUN apt-get update \
    && apt-get install -y apt-utils gnupg curl build-essential libaio1 software-properties-common locales iputils-ping --no-install-recommends \
    && apt-get install -y \
    apt-transport-https \
    && curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - \
    && curl https://packages.microsoft.com/config/ubuntu/18.04/prod.list > /etc/apt/sources.list.d/mssql-release.list

# Install Dependencies
RUN apt-get update \
    && ACCEPT_EULA=Y apt-get install -y \
    unixodbc \
    unixodbc-dev \
    libgss3 \
    odbcinst \
    msodbcsql17 \
    locales \
	freetds-bin \
	freetds-dev \
	freetds-common \
	libct4 \
	libsybdb5 \
	tdsodbc \
    && echo "en_US.UTF-8 UTF-8" > /etc/locale.gen && locale-gen


RUN docker-php-ext-configure pdo_dblib \
	   --with-libdir=/lib/x86_64-linux-gnu/  \
    && docker-php-ext-install pdo_dblib

# Install pdo_sqlsrv and sqlsrv from PECL. Replace pdo_sqlsrv-4.1.8preview with preferred version.
RUN pecl install pdo_sqlsrv sqlsrv \
    && docker-php-ext-enable pdo_sqlsrv sqlsrv

RUN set -ex \
    && { \
            apt-get install -y libpng-dev libjpeg-dev libfreetype6-dev; \
            rm -rf /var/lib/apt/lists/*; \
       }

RUN docker-php-ext-configure gd \
        --with-freetype-dir=/usr/include/freetype2 \
        --with-png-dir=/usr/include \
        --with-jpeg-dir=/usr/include

RUN docker-php-ext-install gd \
    && docker-php-ext-enable opcache

RUN set -ex \
    && { \
            apt-get update ; \
            apt-get install -y libmemcached-dev; \
            rm -rf /var/lib/apt/lists/*; \
       }

RUN set -ex && \
    { \
            pecl install igbinary && \
            pecl install --nobuild memcached && \
            cd "$(pecl config-get temp_dir)/memcached" && \
            phpize && \
            ./configure --enable-memcached-igbinary && \
            make -j$(nproc) && \
            make install; \
    } && \
    docker-php-ext-enable igbinary memcached


RUN set -ex \
    && { \
			apt-get update ; \
            apt-get install -y zlib1g-dev libicu-dev; \
            rm -rf /var/lib/apt/lists/*; \
       }

RUN docker-php-ext-configure intl \
    && docker-php-ext-install intl

RUN set -ex && \
    { \
            pecl install xdebug; \
    }

# XML
RUN set -ex \
    && { \
        apt-get update ; \
        apt-get install -y libxml2-dev; \
        rm -rf /var/lib/apt/lists/*; \
        docker-php-ext-install soap; \
    }

# SSH
RUN set -ex \
    && { \
            apt-get update ; \
            apt-get install -y libssl-dev libssh2-1-dev git; \
            rm -rf /var/lib/apt/lists/*; \
            pecl install ssh2-1.3.1; \
            docker-php-ext-enable ssh2; \
       }

# ZIP
RUN set -ex \
    && { \
        apt-get update ; \
        apt-get install -y libzip-dev libzip4; \
        docker-php-ext-configure zip --with-zlib-dir=/usr; \
        docker-php-ext-install zip; \
        docker-php-ext-enable zip; \
    }

# BC MATH
RUN docker-php-ext-install bcmath;

# PCNTL
RUN docker-php-ext-install pcntl

FROM markkimsal/phusion-serverimage:0.11-debian-buster
RUN install_clean nginx

COPY --from=fpm /usr/local/ /usr/local/
COPY --from=fpm /usr/bin/ /usr/bin/
COPY --from=fpm /usr/lib/x86_64-linux-gnu/libargon*.so.1   \
                /usr/lib/x86_64-linux-gnu/libxml*.so.2     \
                /usr/lib/x86_64-linux-gnu/libicu*.so.63    \
                /usr/lib/x86_64-linux-gnu/libsodium*.so.23 \
                /usr/lib/x86_64-linux-gnu/libsql*.so.0     \
                /usr/lib/x86_64-linux-gnu/libodbc*.so      \
                /usr/lib/x86_64-linux-gnu/libpng*.so       \
                /usr/lib/x86_64-linux-gnu/libjpeg*.so      \
                /usr/lib/x86_64-linux-gnu/libfreet*.so     \
                /usr/lib/x86_64-linux-gnu/libzip*.so.4     \
                /usr/lib/x86_64-linux-gnu/libmemcached*.so \
                /usr/lib/x86_64-linux-gnu/
# COPY --from=fpm /usr/lib/x86_64-linux-gnu/libmemcached*.so /usr/lib/x86_64-linux-gnu/
COPY --from=fpm /usr/lib/x86_64-linux-gnu/libsyb*.so       /usr/lib/x86_64-linux-gnu/
COPY --from=fpm /opt/microsoft/ /opt/microsoft/
RUN echo '/opt/microsoft/msodbcsql17/lib64/' > /etc/ld.so.conf.d/msodbcsql.conf
RUN ldconfig

COPY --from=fpm /etc/odbc* /etc/
COPY --from=fpm /etc/ODBC* /etc/

COPY runit /etc/service/

WORKDIR /app
CMD ["/sbin/my_init"]
