FROM php:8.0.15-fpm-buster as fpm
ARG WITH_TENSOR=""
ARG WITH_SAMBA=""
ARG WITH_SQLSRV=""
ARG WITH_GRPC=""
ARG WITH_IMAGICK=""
ARG WITH_GMAGICK=""

# MYSQL
RUN docker-php-ext-install pdo pdo_mysql mysqli

# PGSQL
RUN set -ex \
    && { \
			apt-get update ; \
            apt-get install -y libpq-dev; \
            rm -rf /var/lib/apt/lists/*; \
            docker-php-ext-install pdo pdo_pgsql; \
       }


# MSSQL
# Add Microsoft repo for Microsoft ODBC Driver 13 for Linux
RUN set -ex \
	&&  if [ ! -z "$WITH_SQLSRV" ] ; then { \
		apt-get update ; \
		apt-get install -y apt-utils gnupg curl build-essential libaio1 software-properties-common locales iputils-ping --no-install-recommends; \
		apt-get install -y apt-transport-https; \
		curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - ; \
		curl https://packages.microsoft.com/config/ubuntu/18.04/prod.list > /etc/apt/sources.list.d/mssql-release.list; \
	}; fi

# MSSQL
# Install Dependencies
RUN set -ex \
	&&  if [ ! -z "$WITH_SQLSRV" ] ; then { \
		apt-get update; \
		ACCEPT_EULA=Y apt-get install -y \
		unixodbc \
		unixodbc-dev \
		libgss3 \
		odbcinst \
		msodbcsql17 \
		locales \
		freetds-bin \
		freetds-dev \
		freetds-common \
		libct4 \
		libsybdb5 \
		tdsodbc \
		&& echo "en_US.UTF-8 UTF-8" > /etc/locale.gen && locale-gen; \
	}; fi


# MSSQL
# Enable extensions
# Install pdo_sqlsrv and sqlsrv from PECL. Replace pdo_sqlsrv-4.1.8preview with preferred version.
RUN set -ex \
	&&  if [ ! -z "$WITH_SQLSRV" ] ; then { \
		docker-php-ext-configure pdo_dblib \
		--with-libdir=/lib/x86_64-linux-gnu/;  \
		docker-php-ext-install pdo_dblib; \
		pecl install pdo_sqlsrv sqlsrv; \
		docker-php-ext-enable pdo_sqlsrv sqlsrv; \
	}; fi


## ZIP
RUN set -ex \
    && { \
        apt-get update ; \
        apt-get install -y libzip-dev libzip4; \
        rm -rf /var/lib/apt/lists/*; \
        docker-php-ext-configure zip --with-zip; \
        docker-php-ext-install zip; \
    }

## GD
RUN set -ex \
    && { \
			apt-get update ; \
            apt-get install -y libpng-dev libjpeg-dev libfreetype6-dev libwebp-dev; \
            rm -rf /var/lib/apt/lists/*; \
            docker-php-ext-configure gd \
            --with-freetype \
            --with-jpeg \
            --with-webp; \
            docker-php-ext-install gd; \
       }


## OPCACHE
RUN set -ex \
    && { \
    		docker-php-ext-enable opcache; \
	}

## memcached
RUN set -ex \
    && { \
            apt-get update ; \
            apt-get install -y libmemcached-dev; \
            rm -rf /var/lib/apt/lists/*; \
       }

RUN set -ex && \
    { \
            pecl install igbinary && \
            pecl install --nobuild memcached && \
            cd "$(pecl config-get temp_dir)/memcached" && \
            phpize && \
            ./configure --enable-memcached-igbinary && \
            make -j$(nproc) && \
            make install; \
    } && \
    docker-php-ext-enable igbinary memcached

## INTL - money_format
RUN set -ex \
    && { \
            apt-get update ; \
            apt-get install -y zlib1g-dev libicu-dev; \
            rm -rf /var/lib/apt/lists/*; \
            docker-php-ext-configure intl \
               && docker-php-ext-install intl; \
       }


## XDEBUG
RUN set -ex && \
    { \
            pecl install xdebug; \
    }

# XML
RUN set -ex \
    && { \
        apt-get update ; \
        apt-get install -y libxml2-dev; \
        rm -rf /var/lib/apt/lists/*; \
        docker-php-ext-install soap; \
    }


## SOAP
RUN set -ex \
    && { \
        apt-get update ; \
        apt-get install -y libxml2-dev; \
        rm -rf /var/lib/apt/lists/*; \
        docker-php-ext-install soap; \
    }

# SSH
RUN set -ex \
    && { \
        apt-get update ; \
        apt-get install -y libssl-dev libssh2-1-dev git; \
        rm -rf /var/lib/apt/lists/*; \
        pecl install ssh2-1.3.1; \
        docker-php-ext-enable ssh2; \
       }

# BC MATH
RUN docker-php-ext-install bcmath;

# PCNTL
RUN docker-php-ext-install pcntl

# LIBSODIUM
RUN set -ex \
    && { \
        apt-get update ; \
        apt-get install -y libsodium-dev libsodium23; \
        rm -rf /var/lib/apt/lists/*; \
        pecl install libsodium; \
        docker-php-ext-enable sodium; \
   }

RUN mkdir /optionallibs;
RUN mkdir /optionaletc;

RUN set -ex \
	&&  if [ ! -z "$WITH_SQLSRV" ] ; then \
		cp /usr/lib/x86_64-linux-gnu/libodbc.so.2      \
			/usr/lib/x86_64-linux-gnu/libodbccr.so.2   \
			/usr/lib/x86_64-linux-gnu/libodbcinst.so.2 \
			/usr/lib/x86_64-linux-gnu/libsybdb*.so.5   \
			/optionallibs/; \
		cp -r /etc/odbc* /optionaletc/; \
		cp -r /etc/ODBC* /optionaletc/; \
	fi

#RUN echo '/opt/microsoft/msodbcsql17/lib64/' > /etc/ld.so.conf.d/msodbcsql.conf


# TENSOR
RUN set -ex \
    &&  if [ ! -z "$WITH_TENSOR" ] ; then \
        apt-get update ; \
        apt-get install -y libopenblas-dev liblapacke-dev re2c gfortran; \
        pecl install tensor; \
        docker-php-ext-enable tensor; \
        cp /usr/lib/x86_64-linux-gnu/libopenblas.so.0    \
            /usr/lib/x86_64-linux-gnu/libblas.so.3       \
            /usr/lib/x86_64-linux-gnu/liblapacke.so.3    \
            /usr/lib/x86_64-linux-gnu/liblapack.so.3     \
            /usr/lib/x86_64-linux-gnu/libgfortran.so.5   \
            /usr/lib/x86_64-linux-gnu/libquadmath.so.0   \
            /usr/lib/x86_64-linux-gnu/libtmglib.so.3     \
            /optionallibs/ \
    ;fi

# GRPC
RUN set -ex \
    &&  if [ ! -z "$WITH_GRPC" ] ; then \
        apt-get update ; \
        apt-get install -y zlib1g-dev; \
        pecl install grpc; \
        pecl install protobuf; \
        docker-php-ext-enable grpc; \
        docker-php-ext-enable protobuf; \
    fi

# IMAGICK
RUN set -ex \
    &&  if [ ! -z "$WITH_IMAGICK" ] ; then \
        apt-get update; \
        apt-get install -y libgraphicsmagick1-dev libmagickwand-6-headers libmagickwand-dev; \
        pecl install imagick; \
        docker-php-ext-enable imagick; \
		cp /usr/lib/x86_64-linux-gnu/libMagickWand-6.Q16.so.6  \
			/usr/lib/x86_64-linux-gnu/libMagickCore-6.Q16.so.6 \
			/usr/lib/x86_64-linux-gnu/libgomp.so.1 \
			/usr/lib/x86_64-linux-gnu/liblcms2.so.2 \
			/usr/lib/x86_64-linux-gnu/liblqr-1.so.0 \
			/usr/lib/x86_64-linux-gnu/libfftw3.so.3 \
			/usr/lib/x86_64-linux-gnu/libXext.so.6 \
			/usr/lib/x86_64-linux-gnu/libltdl.so.7 \
			/usr/lib/x86_64-linux-gnu/libgomp.so.1 \
			/optionallibs/; \
    fi

