FROM markkimsal/php:8.0.10-fpm as fpm
FROM markkimsal/phusion-serverimage:0.11-debian-buster
ARG WITH_SAMBA
ARG WITH_SQLSRV
ARG WITH_TENSOR

RUN install_clean nginx
COPY runit /etc/service/
COPY start-container /usr/local/bin/start-container
RUN chmod a+x /usr/local/bin/start-container
RUN chown -R www-data /var/www
RUN mkdir /app && chown www-data /app

COPY --from=fpm /usr/local/ /usr/local/
COPY --from=fpm /usr/lib/x86_64-linux-gnu/libargon*.so.1   \
                /usr/lib/x86_64-linux-gnu/libxml2.so.2     \
                /usr/lib/x86_64-linux-gnu/libicu*.so.63.1  \
                /usr/lib/x86_64-linux-gnu/libsodium*.so.23 \
                /usr/lib/x86_64-linux-gnu/libsql*.so.0     \
                /usr/lib/x86_64-linux-gnu/libpng*.so       \
                /usr/lib/x86_64-linux-gnu/libzip*.so       \
                /usr/lib/x86_64-linux-gnu/libjpeg*.so      \
                /usr/lib/x86_64-linux-gnu/libfreet*.so     \
                /usr/lib/x86_64-linux-gnu/libmemcached*.so \
                /usr/lib/x86_64-linux-gnu/libonig.so.5.0.0 \
                /usr/lib/x86_64-linux-gnu/libpq.so.5 \
                /usr/lib/x86_64-linux-gnu/

#MSSQL
#COPY --from=fpm /optionallibs/* \
#                /usr/lib/x86_64-linux-gnu/


#MSSQL
#COPY --from=fpm /usr/lib/x86_64-linux-gnu/libodbc*.so.2     \
#                /usr/lib/x86_64-linux-gnu/libodbcinst*.so.2 \
#                /usr/lib/x86_64-linux-gnu/libsybdb*.so.5    \
#                /usr/lib/x86_64-linux-gnu/
#
COPY --from=fpm /opt/microsoft/ /opt/microsoft/
RUN echo '/opt/microsoft/msodbcsql17/lib64/' > /etc/ld.so.conf.d/msodbcsql.conf


# TENSOR
#COPY --from=fpm /usr/lib/x86_64-linux-gnu/libopenblas*.so.0   \
#                /usr/lib/x86_64-linux-gnu/libblas*.so.3    \
#                /usr/lib/x86_64-linux-gnu/liblapacke*.so.3    \
#                /usr/lib/x86_64-linux-gnu/liblapack*.so.3    \
#                /usr/lib/x86_64-linux-gnu/libgfortran*.so.5   \
#                /usr/lib/x86_64-linux-gnu/libquadmath*.so.0   \
#                /usr/lib/x86_64-linux-gnu/libtmglib*.so.3   \
#                /usr/lib/x86_64-linux-gnu/

RUN ldconfig

WORKDIR /app
CMD ["/usr/local/bin/start-container"]
