#!/bin/bash

if [ -f ./.env ]; then
    source ./.env
fi

COMPOSER_VERSION=${COMPOSER_VERSION:-"2.0"}
# you can use composer standard image, but you might have to add --ignore-platform-reqs
COMPOSER_IMAGE=${COMPOSER_IMAGE:-"markkimsal/phusion-php:8.0-builder"}

docker run --rm -ti \
    -u www-data \
    -e WWWUID: ${WWWUID:-1000}
    -e WWWGID: ${WWWGID:-1000}
    -e 'COMPOSER_HOME=/var/lib/html'
    -v $(pwd):/app \
    -v $HOME/.composer:/var/lib/html/.composer \
    -w /app \
     composer "$@"
