#!/bin/bash

if [ -f ./.env ]; then
    source ./.env
fi

APP_SERVICE=${APP_SERVICE:-"webapp"}

docker-compose exec \
    -e "ENV_KEY=${ENV_KEY}" \
    -e "XDEBUG_TRIGGER=1" \
    "$APP_SERVICE" \
    php -d 'zend_extension=xdebug.so' -d 'xdebug.mode=develop'  "$@"
