#!/bin/bash

if [ -f ./.env ]; then
    source ./.env
fi

APP_SERVICE=${APP_SERVICE:-"webapp"}

docker-compose exec \
    "$APP_SERVICE" \
    php \
    -d 'zend_extension=xdebug.so' \
    -d 'xdebug.mode=debug,coverage' \
    -d 'xdebug.client_host=host.docker.internal' \
    -d 'xdebug.client_port=10427' \
    -d 'xdebug.discover_client_host=1' \
    -d 'xdebug.remote_handler=dbgp' \
    -d 'xdebug.start_with_request=yes' \
   ./vendor/bin/phpunit "$@"
